{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "94d6a845_23e5e09f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1040213
      },
      "writtenOn": "2022-05-23T21:46:44Z",
      "side": 1,
      "message": "Thanks for the bug fix!  Can you please open a bug and take a bugreport during the call when the volume problem occurs?  Keep the call alive during the bugreport and upload.  Thanks!",
      "revId": "a8048b95e5e0c6ed68e5c5b32ff743208ca2ffce",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}