{
  "comments": [
    {
      "key": {
        "uuid": "ddcf92a6_bbb4910f",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 10,
      "author": {
        "id": 1402585
      },
      "writtenOn": "2020-09-28T13:25:59Z",
      "side": 1,
      "message": "Should this CL also be under Bug: 169202556 ?",
      "revId": "ea91db445c197b23389437ff473a0b420d0a2336",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}